apiVersion: v1
kind: Service
metadata:
  name: go-k8s-cognito-crud-microservice-template
  namespace: template-k8s-cognito
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9001
      targetPort: 9001
  selector:
    app: go-k8s-cognito-crud-microservice-template